### ISSUE TITLE
Error: Cannot find module './0AuthParameters'

### ISSUE THREAD

**Issue by SimeonGriggs** [robmarshall/gatsby-source-gravityforms#13]
Error trying to deploy to Netlify

```
5:27:03 PM: error Cannot find module './0AuthParameters'
5:27:03 PM: Error in "/opt/build/repo/node_modules/gatsby-source-gravityforms/gatsby-node.js": Cannot find module './0AuthParameters'
5:27:03 PM: See our docs page for more info on this error: https://gatsby.dev/issue-how-to
5:27:03 PM: 
5:27:03 PM:   Error: Cannot find module './0AuthParameters'
```

* In: `/utils/axios.js`
* Line 20 is `const _require3 = require('./0AuthParameters'),` 
* But the filename is `0authParameters.js`

**Comment by robmarshall** [comment]
Hmm, weird. I'll take a look at this either later tonight or tomorrow morning.

Is it compiling fine on your local?

**Comment by SimeonGriggs** [comment]
Yeah it is. Only an issue once it goes to Netlify.

**Comment by robmarshall** [comment]
Hey, 

Seems that local builds could overlook a slight typo (not sure how) but Netlify couldn't.

Either way, it should work now. Update your package to 12 and give it another try:
`"gatsby-source-gravityforms": "^1.0.12"`

Let me know,
Cheers

**Comment by SimeonGriggs** [comment]
Hey, I was just about to submit a PR :D

Working beautifully now. Thanks mate.

**Comment by robmarshall** [comment]
I'd love to see how you manage the data if possible? I'm currently filling out a component to take the form data but always needs new eyes.

**Comment by SimeonGriggs** [comment]
Sure. I started building my own Component for now but it's super basic and not even hooked up to send yet. Check your email...

**Comment by robmarshall** [comment]
This might help move you in the right direction: https://github.com/robmarshall/gatsby-gravityforms-component
