### ISSUE TITLE
403 error status

### ISSUE THREAD

**Issue by SilencerWeb** [robmarshall/gatsby-source-gravityforms#15]
I'm trying to set up gatsby-source-gravityforms but get 403 error status but can't understand why.

Configurations I tried:
```js
    {
      resolve: 'gatsby-source-gravityforms',
      options: {
        baseUrl: `${process.env.WORDPRESS_PROTOCOL}://${process.env.WORDPRESS_BASE_URL}`,
        api: {
          key: process.env.GRAVITY_FORMS_KEY,
          secret: process.env.GRAVITY_FORMS_SECRET,
        },
      },
    },
```
```js
    {
      resolve: 'gatsby-source-gravityforms',
      options: {
        baseUrl: `${process.env.WORDPRESS_PROTOCOL}://${process.env.WORDPRESS_BASE_URL}`,
        api: {
          key: process.env.GRAVITY_FORMS_KEY,
          secret: process.env.GRAVITY_FORMS_SECRET,
        },
        basicAuth: {
          username: process.env.WORDPRESS_USER,
          password: process.env.WORDPRESS_PASSWORD,
        },
      },
    },
```

Access to API is enabled, the key is generated correctly and added to `.env`:

![image](https://user-images.githubusercontent.com/20713191/62420486-6b292700-b6ac-11e9-9b57-864a7f2d607b.png)

Error in the terminal:

![image](https://user-images.githubusercontent.com/20713191/62420608-75e4bb80-b6ae-11e9-9363-b6ab446aa95f.png)

`gatsby-source-gravityforms` version is `1.0.13`.

Any ideas why it works like that? And why is `expires` value is `'Wed, 11 Jan 1984 05:00:00 GMT'`?

**Comment by robmarshall** [comment]
Hey,

If you console log out the variables in Gatsby node, check that they are pulling through.

Let me know how that goes.

Cheers

**Comment by SilencerWeb** [comment]
@robmarshall, yes, they are pulling through, otherwise, I wouldn't open an issue :)

**Comment by robmarshall** [comment]
The reason I ask is that is a Gravity Forms API error. Generally corresponds with incorrect details, or incorrect roles.

The plugin is able to see the site, as you are getting a response. But not able to connect.

Would you be happy creating a new set of creds for me to test my end? Maybe I can narrow down the problem?

**Comment by SilencerWeb** [comment]
@robmarshall, is key and secret enough with the ability only to read?

**Comment by robmarshall** [comment]
key/secret as read only, Base URL and any basic auth you have set up.

No need to write :)

**Comment by SilencerWeb** [comment]
@robmarshall, sorry, we fixed the problem, it was on our side, the api user has the role "subscriber" and didn't have access to gravity forms :)

**Comment by robmarshall** [comment]
I'm glad it's working for you :)
