### ISSUE TITLE
Is there a way to get Site Key for reCAPTCHA?

### ISSUE THREAD

**Issue by SilencerWeb** [robmarshall/gatsby-source-gravityforms#16]
Because right now fetching reCAPTCHA makes no sense if you can't get Site Key. Yes, you can store it in `.env` variables but what's the point if it already exists in Gravity Forms settings? Or there is no way to get it?

**Comment by robmarshall** [comment]
I am not sure the GF API extends that far.

https://docs.gravityforms.com/rest-api-v2/#path

If you know how to connect to the settings that would be a great help. Submit a PR with your solution and I can then extend it to the rest of the settings.

Cheers

**Comment by SilencerWeb** [comment]
@robmarshall, got it, thanks!
