### ISSUE TITLE
Can't query field "content"

### ISSUE THREAD

**Issue by adsoink** [robmarshall/gatsby-source-gravityforms#17]
Hey Rob,

Closed our other issue, and right now chewing on the GraphiQL and curious why the field "content" is missing. The rest of the query validates with the exception of the field for "content".

Ideas?

Cheers,

Travis

**Comment by robmarshall** [comment]
Where is the content coming from? What is the field? Do you mean html_content?

**Comment by adsoink** [comment]
The content is coming from the Gravity Forms API, and "content" is a field listed in your example query. Using it as reference, and the query fails when "content" is included. There is no field for "html_content" available in the GF API.

**Comment by robmarshall** [comment]
Ah, I see.

Those are the recommended fields to query, but it depends on the field to what is populated. GraphQL does not allow optional fields.

If you see this file from my example component, it outlines a way to build out fields.

https://github.com/robmarshall/gatsby-gravityforms-component/blob/4f47d2b0367cf8d781f13fda3d782661e3e47cdb/src/container/FieldBuilder/index.js

The HTML field is the one with content. No other fields (that come to mind) need an admin user to populate.

I hope that makes sense.

**Comment by robmarshall** [comment]
What this does do, it highlight a need for a schema to be defined before any forms are created by the plugin. 

This will then stop any errors like this when a field has not been added. It would just return an empty string.

You wouldn't happen to have a spare hour to implement would you ;)

**Comment by adsoink** [comment]
I have the rest of the day to dial this in. How can I help?

**Comment by robmarshall** [comment]
A JSON schema would need to be created that holds all the return keys with empty strings (or null if it works. Would be cleaner). These keys are shown in the example inside FormFields (including the content field you couldn't query)

As the plugin maps over the fields from the API, it will either apply the value to the correct key or leave it empty. This should stop any query errors.

**Comment by adsoink** [comment]
I can query the API no problem. Am able to see the fields and their schema too when I drop "content" from the query. 

Sadly not finding your reply or example helpful. If I can easily return the fields, labels, schema, IDs, etc... why is the "content" field necessary for the query? Shouldn't the flow be as simple as mapping the individual fields by ID and then creating a POST so the response is written back to the Gravity Forms API?

**Comment by robmarshall** [comment]
It sounds like you do not need a content field, as GF is not populating it. My example allows people a quick copy/paste solution to then edit.

My schema PR suggestion would eliminate the solution/example problem you are currently having for future users. But right now you can just remove content from your query.

In terms of posting a response, I would recommend taking a look at my component plugin for pointers.

**Comment by adsoink** [comment]
The forms I'm working with now have no content outside of the form fields and one small piece of conditional logic.

I've been working with the component plugin and have used your example to guide my efforts with integration and display. Despite best efforts, nothing displays. I'm again left wondering why the input fields aren't mapped directly to the API, and then written back to Gravity Forms on submit. All of this feels overly complicated for what feels like a relatively simple process. 

I may have to jump ship on this and implement Contact Form 7 instead. Working with the endpoints and generally the integration is a lot more straightforward.

**Comment by robmarshall** [comment]
This is a source plugin. Its aim is to turn GF forms into GraphQL content. It also passes down the API URL for you to handle the data yourself. How you build it is entirely up to you.

It is still early days for it, and conditional logic has not yet been implemented. If you are wanting to use pure API then Gravity Forms can do that, but you will still struggle with passing back data from a static site without the use of a Lands function or third party management.

I wish you the best of luck.

**Comment by adsoink** [comment]
I understand that, and it isn't returning anything usable. Thanks very much for your efforts, and I will watch for this to mature.
