### ISSUE TITLE
Get conditionalLogic for formFields?

### ISSUE THREAD

**Issue by SilencerWeb** [robmarshall/gatsby-source-gravityforms#18]
Right now can't see how to get conditionalLogic for formFields :(

Pretty sure it does exist, I checked it in docs

I wouldn't even mind helping with PR to speed up the process if you wouldn't mind helping me with pointing out where to do it :)

**Comment by robmarshall** [comment]
Hey,

Conditional logic has not been added yet. It would be great if you could get involved!

I would start by forking it, connecting to a local install and taking a loop at the GF fields passed to the plugin.

Take a look at this file:
https://github.com/robmarshall/gatsby-source-gravityforms/blob/master/src/gatsby-node.js

Line 50 all forms and fields are brought in. A good place to inspect.

Process forms is where everything is converted
https://github.com/robmarshall/gatsby-source-gravityforms/blob/master/src/utils/processForms.js

I suppose a key needs adding to the field object, relating the fields by ID?

**Comment by SilencerWeb** [comment]
@robmarshall, got it.

What about testing? How to do that?

**Comment by robmarshall** [comment]
Create a tester Gatsby app (maybe clone this, that I use : https://github.com/robmarshall/gatsby-gravity-forms-sandbox)

Also clone this plugin.

Then link the plugin, to the tester site using Yarn Link.
1. Go to plugin root, type "yarn link"
2. It will give you a command. Probably "yarn link gatsby-source-gravityforms"
3. Go to your test site root, and enter that command

Now any changes that are made in the plugin, automatically push to the build.

To compile the plugin as you build
yarn watch
