### ISSUE TITLE
Add build steps

### ISSUE THREAD

**Issue by hu0p** [robmarshall/gatsby-source-gravityforms#6]
There are currently installation procedures that appear to suggest that using this plugin is as easy as installing the package and adding the config to gatsby-config.js. However, the presence of the `src/` folder and .babelrc suggest a transpile step. 

Can you elaborate on those?

**Comment by robmarshall** [comment]
I wonder if it would be better to change the prepare script to prepublish, so the final packaged files are ready on NPM. Might fix this issue.

**Comment by hu0p** [comment]
Hey Rob, I just submitted a [new PR](https://github.com/robmarshall/gatsby-source-gravityforms/pull/8) that should clear up the problem. I looked into prepublish as you noted, but as far as I can tell, prepublish has been [deprecated in favor of prepare](https://docs.npmjs.com/misc/scripts). It doesn't help that their documentation really details the implementation more than the use-case for each event. 

Anyway, if you pull down that PR, run an `npm i` per the usual procedure and then an `npm pack`, it will output a tarball with which you can verify that the package is structured as desired. 

I hope this helps. Sorry it's been such a pain to get it distributed properly. Thanks for the great work on putting this source plugin together!

**Comment by robmarshall** [comment]
Ah ha! Good find. Ill publish the update to NPM now. Thanks for the help :)
